name: Resize Images

on:
  pull_request:
    branches:
      - automate-read-more
    # paths:
    #   - "**.jpg"
    #   - "**.jpeg"
    #   - "**.png"
    #   - "**.gif"
  # push:
  #     branches:
  #       - automate-read-more
jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
