name: Schedule Job using Carbon Aware API

on: 
  push:
    branches:
      - gh-pages
      
  workflow_dispatch:

jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jhcoll/carbon-aware-schedule-action@main
        with:
            region: 'eastus'
            template-paths: 'templates/template.yml'
      - name: Commit scheduled workflow
        run: |
           git config --global user.name 'jhcoll'
           git config --global user.email 'jhcoll@users.noreply.github.com'
           git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/jhcoll/blog
           git checkout "${GITHUB_REF:11}"
           git add .github/workflows/template.yml
           git commit -m "scheduled workflow"
           git push