name: Schedule Job using Carbon Aware API

on: 
  push:
    branches:
      - gh-pages
      
  workflow_dispatch:

jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - uses: jhcoll/carbon-aware-schedule-action@main
        with:
            region: 'eastus'
            template-paths: 'templates/template.yml'
      - name: Commit scheduled workflow
        run: |
           git add .github/workflows/template.yml
           git commit -m "scheduled workflow"
           git push